/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;
import java.sql.*;
import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;

/**
 *
 * @author bryan
 */
public class Administrador extends javax.swing.JFrame {
    
    String user, nombreUsuario;
    public static int sesionUsuario;

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        user = Login.user;
        sesionUsuario = 1;
        
        setSize(650, 430);
        setResizable(false);
        setTitle("Administrador - Sesión de " + user);
        setLocationRelativeTo(null);
        
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        
          ImageIcon wallpaper = new ImageIcon("src/img/wallpaperPrincipal.jpg");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jlbWallpaper.getWidth(), jlbWallpaper.getHeight(), Image.SCALE_DEFAULT));
        jlbWallpaper.setIcon(icono);
        this.repaint();
        
        try {
            Connection conn = Conexion.conectar();
            PreparedStatement pst = conn.prepareCall(
                "SELECT NOMBRE_USUARIO FROM USUARIOS WHERE USERNAME = '" + user + "'"
            );
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                nombreUsuario = rs.getString("NOMBRE_USUARIO");
                jlbNombreUsuario.setText(nombreUsuario);
            }
                    
        } catch (SQLException e) {
            System.err.println("Error de conexion desde la interfaz de administrador: " + e.getMessage());
        }
    
    }
    
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon.png"));
      return retValue;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbNombreUsuario = new javax.swing.JLabel();
        btnRegistrarUsuario = new javax.swing.JButton();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnCreatividad = new javax.swing.JButton();
        btnCapturista = new javax.swing.JButton();
        btnTecnico = new javax.swing.JButton();
        btnAcercaDe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbNombreUsuario.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlbNombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jlbNombreUsuario.setText("jLabel1");
        getContentPane().add(jlbNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnRegistrarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/addUser.png"))); // NOI18N
        getContentPane().add(btnRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 100));

        btnGestionarUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/informationuser.png"))); // NOI18N
        getContentPane().add(btnGestionarUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 100));

        btnCreatividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/creatividad.png"))); // NOI18N
        getContentPane().add(btnCreatividad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 120, 100));

        btnCapturista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/capturista.png"))); // NOI18N
        getContentPane().add(btnCapturista, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 120, 100));

        btnTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tecnico.png"))); // NOI18N
        getContentPane().add(btnTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 120, 100));

        btnAcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/geekipedia.png"))); // NOI18N
        getContentPane().add(btnAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 120, 100));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestionar usuarios");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Creatividad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 170, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Panel vista capturista");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Panel vista técnico");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Acerca de");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        jLabel7.setText("Creado por Alan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, -1, -1));

        jlbWallpaper.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jlbWallpaper.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jlbWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcercaDe;
    private javax.swing.JButton btnCapturista;
    private javax.swing.JButton btnCreatividad;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JButton btnRegistrarUsuario;
    private javax.swing.JButton btnTecnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlbNombreUsuario;
    private javax.swing.JLabel jlbWallpaper;
    // End of variables declaration//GEN-END:variables
}
