/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WineStoreDB;

import static WineStoreDB.InsertPurchase.RET_CANCEL;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author bryan
 */
public class editarCompras extends javax.swing.JDialog {

    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;
    private final Database db;
    private final HashMap ht1;
    double totalwine;
    String clienteid;
    Date fecha;
    String preciototal;
    String cantidadbotellas;
    String idvino;
    String nombre;
    String apellido;
    String nombrev;
    String precio;

    public editarCompras(java.awt.Frame parent, Database db) {

        super(parent, true);
        initComponents();
        this.db = db;
        ht1 = new HashMap<String, Integer>();
        total.setText("0.00");

        // Construir el combo con el ID y Nombre de proveedor
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
        total.setText("");

        this.setLocationRelativeTo(null);
    }

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }
    private int returnStatus = RET_CANCEL;

    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        idcompra = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        idcliente = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jnombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idwine = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jvino = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jfecha = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar compras");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Compras", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("ID compra:");

        idcompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idcompraKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idcompraKeyTyped(evt);
            }
        });

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idcompra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(idcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("ID cliente:");

        idcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idclienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idclienteKeyTyped(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jnombre.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre del cliente:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("ID Vino:");

        idwine.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idwineKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idwineKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nombre del vino:");

        jvino.setEditable(false);

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Fecha de la compra:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 102));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jnombre)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(idwine, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jvino)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(107, 107, 107))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(idwine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jvino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cantidad:");

        cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cantidadKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total:");

        total.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total.setForeground(new java.awt.Color(0, 0, 204));
        total.setText("0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(total))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String idc = idcompra.getText();

            if (idc.isEmpty() || idc.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Campo vacío, ingrese ID de compra para editar.");

            } else if (validacionDatosID(idc) == 0) {
                JOptionPane.showMessageDialog(rootPane, "El ID= " + idc + " no se encuentra en la base de datos.");
            } else {
                String sql = String.format("select * from winestore.purchases where purchase_id = %s", idc);

                try {

                    ht1.clear();
                    ResultSet rs = db.query(sql);
                    //String selet = "Seleccionar";
                    //  comboName.addItem(selet);
                    while (rs.next()) {
                        clienteid = rs.getString(2);
                        fecha = rs.getDate(3);
                        preciototal = rs.getString(4);
                        cantidadbotellas = rs.getString(5);
                        idvino = rs.getString(6);
                        String amlo = jalarNombre(clienteid);
                        String anaya = jalarVino(idvino);

                        idcliente.setText(clienteid);
                        jnombre.setText(amlo);
                        jvino.setText(anaya);
                        total.setText(preciototal);
                        jfecha.setDate(fecha);
                        cantidad.setText(cantidadbotellas);
                        idwine.setText(idvino);
                    }
                } catch (SQLException ex) {
                    System.out.println(ex.getMessage());
                }

            }
        } catch (SQLException ex) {
            Logger.getLogger(editarCompras.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void idcompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idcompraKeyTyped
        // TODO add your handling code here:

        int limit = 5;
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden ingresar números.");
        }
        if (idcompra.getText().length() == limit) {
            evt.consume();
            getToolkit().beep();
        }


    }//GEN-LAST:event_idcompraKeyTyped

    private void idcompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idcompraKeyReleased
        // TODO add your handling code here:
        String idc = idcompra.getText().toString();
        jLabel8.setText("");

        if (!idc.equals("")) {
            try {
                if (validacionDatosID(idc) != 0) {
                    System.out.println("");
                    jLabel8.setText("ID valido.");
                } else {
                    jLabel8.setText("ID no existente.");
                    idcliente.setText("");
                    jnombre.setText("");
                    jvino.setText("");
                    total.setText("");
                    jfecha.setDate(null);
                    cantidad.setText("");
                    idwine.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(DeleteWinesID.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_idcompraKeyReleased

    private void idclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idclienteKeyReleased
        // TODO add your handling code here:
        String idc = idcliente.getText().toString();
        jLabel10.setText("");
        jnombre.setText("");

        if (!idc.equals("")) {
            try {
                if (validacionDatos(idc) != 0) {
                    jLabel10.setText("ID valido.");

                    String sql = String.format("select nombre,apellido from winestore.customer where customer_id = %s", idc);

                    try {

                        ht1.clear();
                        ResultSet rs = db.query(sql);
                        //String selet = "Seleccionar";
                        //  comboName.addItem(selet);
                        while (rs.next()) {
                            nombre = rs.getString(1);
                            apellido = rs.getString(2);
                            jnombre.setText(nombre + " " + apellido);

                        }
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
                } else {
                    jLabel10.setText("ID no existente.");
                    jnombre.setText("");
                }
            } catch (SQLException ex) {
                Logger.getLogger(DeleteWinesID.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_idclienteKeyReleased

    private void idclienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idclienteKeyTyped
        // TODO add your handling code here:

        int limit = 5;
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden ingresar números.");
        }
        if (idcompra.getText().length() == limit) {
            evt.consume();
            getToolkit().beep();
        }

    }//GEN-LAST:event_idclienteKeyTyped

    private void idwineKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idwineKeyTyped
        // TODO add your handling code here:

        int limit = 5;
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden ingresar números.");
        }
        if (idcompra.getText().length() == limit) {
            evt.consume();
            getToolkit().beep();
        }

    }//GEN-LAST:event_idwineKeyTyped

    private void idwineKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idwineKeyReleased
        // TODO add your handling code here:
        String idc = idwine.getText().toString();
        jLabel11.setText("");
        jvino.setText("");

        if (!idc.equals("")) {
            try {
                if (validacionDatosW(idc) != 0) {
                    System.out.println("");
                    jLabel11.setText("ID valido.");
                    String sql = String.format("select wine_name,price from winestore.wine_store where wine_store_id = %s", idc);

                    try {

                        ht1.clear();
                        ResultSet rs = db.query(sql);
                        //String selet = "Seleccionar";
                        //  comboName.addItem(selet);
                        while (rs.next()) {
                            nombrev = rs.getString(1);
                            precio = rs.getString(2);
                            
                            cantidad.setText("1");
                            total.setText(precio);
                            jvino.setText(nombrev);

                        }
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
                } else {
                    jLabel11.setText("ID no existente.");
                    jvino.setText("");
                     cantidad.setText("0");
                            total.setText("0.00");
                    
                }
            } catch (SQLException ex) {
                Logger.getLogger(DeleteWinesID.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_idwineKeyReleased

    private void cantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyReleased
        // TODO add your handling code here:
        String idw = idwine.getText();
        String valor = cantidad.getText();
        String preciow = "";
        jLabel8.setText("");
        if (!idw.equals("")) {
            try {
                if (validacionDatosW(idw) != 0) {
                    System.out.println("");
                    int aux = Integer.parseInt(idw);
                    jLabel8.setText("ID valido.");
                    final String sql = String.format("select price from winestore.wine_store where wine_store_id = %s", idw);

                    try {
                        ResultSet rs = db.query(sql);
                        while (rs.next()) {
                            int id = rs.getInt(1);
                            preciow = rs.getString(1);
                            ht1.put(preciow, id);
                        }
                    } catch (SQLException ex) {
                        System.out.println(ex.getMessage());
                    }
                    double p;
                    char c = evt.getKeyChar();
                    if (!valor.isEmpty()) {
                        p = Double.parseDouble(preciow);
                        double can = Double.parseDouble(valor);
                        totalwine = can * p;
                        String aggh = Double.toString(totalwine);
                        total.setText(aggh);
                    } else {

                        total.setText("0.00");
                    }
                } else {
                    // JOptionPane.showMessageDialog(this, "El vino con id="+idw+" no existe en la base de datos.");
                    jLabel8.setText("El ID no existente.");
                    total.setText("0.00");
                }
            } catch (SQLException ex) {
                Logger.getLogger(InsertPurchase.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_cantidadKeyReleased

    private void cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantidadKeyTyped
        // TODO add your handling code here:
        int limit = 5;
        char c = evt.getKeyChar();
        if ((c < '0' || c > '9') && c != KeyEvent.VK_BACK_SPACE) {
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se pueden ingresar números.");
        }
        if (idcompra.getText().length() == limit) {
            evt.consume();
            getToolkit().beep();
        }

    }//GEN-LAST:event_cantidadKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            // TODO add your handling code here:
            String idc = idcliente.getText();
            String idcom = idcompra.getText();
            String idq = idwine.getText();
            String n = jnombre.getText();
            String amlo = idcliente.getText();
            String bronco = idwine.getText();
            String anaya = total.getText();
            Date meade = jfecha.getDate();
            String pan = cantidad.getText();
            String f = "";
            String dia = "";
            String mes = "";
            String year = "";
            String s = "";

            if (idc.isEmpty() || idc.equals("") || idq.isEmpty() || idq.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Asegurese que los id de cliente y vino sean validos.");
            }else if (pan.isEmpty() || pan.equals("")) {
                JOptionPane.showMessageDialog(rootPane, "El campo cantidad no puede estar vacio.");
            } 
            else if (validacionDatos(idc) == 0 || validacionDatosW(idq) == 0 || validacionDatosID(idcom) == 0) {
                JOptionPane.showMessageDialog(rootPane, "Verifique si todos los ID son validos.");
            } else {

                int input = JOptionPane.showConfirmDialog(rootPane, "¿Desea guardar los cambios al cliente " + n.toUpperCase() + " con ID = " + idcom + "?", "Editar cliente", 0);
                if (input == 0) {
                    dia = Integer.toString(jfecha.getCalendar().get(Calendar.DAY_OF_MONTH));
                    year = Integer.toString(jfecha.getCalendar().get(Calendar.YEAR));
                    mes = Integer.toString(jfecha.getCalendar().get(Calendar.MONTH) + 1);
                    String m = "0";

                   /* if (mes.length() == 1 || dia.length() == 1) {
                        mes = m + mes;

                    }

                    if (dia.length() == 1 || dia.startsWith("0")) {
                        dia = m + dia;
                    }*/
                    f = year + "-" + mes + "-" + dia;

                    StringBuilder sql
                            = new StringBuilder("UPDATE winestore.purchases SET costumer_id = " + amlo + "," + "date_of_purchase='" + f + "'," + "amount_of_purchase=" + anaya + "," + "amount_of_bottles=" + pan + "," + "wine_store_id=" + bronco + " where costumer_id= " + idc);
                    System.out.println(sql);
                    try {
                        db.update(sql.toString());
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, "Error al guardar cambios.");
                        System.out.println(ex.getMessage());
                    }
                    JOptionPane.showMessageDialog(rootPane, "Se han guardado correctamente los cambios.");
                    setVisible(false);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(editarCompras.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        doClose(1);
    }//GEN-LAST:event_jButton3ActionPerformed
    public int validacionDatosID(String vd) throws SQLException {
        String sql1 = "select purchase_id  from winestore.purchases";
        int x = 0;
        try {
            ResultSet rs = db.query(sql1);
            while (rs.next()) {

                String name = rs.getString(1);
                if (name.equalsIgnoreCase(vd)) {
                    x++;
                }

            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return x;
    }

    public int validacionDatos(String vd) throws SQLException {
        String sql1 = "select customer_id  from winestore.customer";
        int x = 0;
        try {
            ResultSet rs = db.query(sql1);
            while (rs.next()) {

                String name = rs.getString(1);
                if (name.equalsIgnoreCase(vd)) {
                    x++;
                }

            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return x;
    }

    public int validacionDatosW(String vd) throws SQLException {
        String sql1 = "select wine_store_id  from winestore.wine_store";
        int x = 0;
        try {
            ResultSet rs = db.query(sql1);
            while (rs.next()) {

                String name = rs.getString(1);
                if (name.equalsIgnoreCase(vd)) {
                    x++;
                }

            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        return x;
    }

    public String jalarNombre(String idn) {
        String sql = "select apellido,nombre from winestore.customer where customer_id = " + idn;
        String n = "";
        try {
            ResultSet rs = db.query(sql);
            while (rs.next()) {
                //int id = rs.getInt(1);
                String apellido = rs.getString(1);
                String name = rs.getString(2);
                n = apellido + " " + name;
                // ht1.put(n, id);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return n;
    }

    public String jalarVino(String idvino) {
        String sql = "select wine_name from winestore.wine_store where wine_store_id = " + idvino;
        String n = "";
        try {
            ResultSet rs = db.query(sql);
            while (rs.next()) {
                //int id = rs.getInt(1);
                // String apellido = rs.getString(1);
                String vino = rs.getString(1);
                n = vino;
                // ht1.put(n, id);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

        return n;
    }

    /* public int jalarNombre(String n){stri
        
        String sql1 = "select nombre  from winestore.purchases";
    
    }*/
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cantidad;
    private javax.swing.JTextField idcliente;
    private javax.swing.JTextField idcompra;
    private javax.swing.JTextField idwine;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.toedter.calendar.JDateChooser jfecha;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jvino;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
